<a href="https://colab.research.google.com/github/Jeronimocalles/analiticadenegocios/blob/main/Reto__1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Caso de estudio**: Detección de Riesgo SARLAFT en una Entidad Financiera


En este documento se desarrolla y analiza un modelo Naive Bayes para fortalecer el sistema de prevención de lavado de activos (SARLAFT) en una entidad financiera utilizando diferentes variables socioeconómicas.

La identificación temprana de clientes con alto riesgo de incurrir en lavado de activos se basa en el análisis del comportamiento financiero y los cambios inusuales en el patrimonio de estos.

De acuerdo con lo anterior, las variables que se analizan son:

**Edad:** Es el número de años de vida de la persona al momento de la evaluación.

**Ingresos_usd:** Es el dinero que recibe la persona como resultado de una actividad comercial (medidos en dólares estadounidenses).

**Gastos_usd:** Son los egresos de una persona medidos en dólares estadounidenses.

**num_tarjetas_credito:** Es la cantidad de tarjetas de crédito que tiene la persona en la entidad financiera al momento de la evaluación.

**Monto_transado_tarjetas_usd:** Es la cantidad de dólares estadounidenses que las perso mueven mensualmente en sus tarjetas del banco.

**Porcentaje_crecimiento_patrimonio:** Es el crecimiento del patrimonio de la persona, expresado en porcentaje. Entendiendo el patrimonio como el conjunto total de sus bienes (materiales e inmateriales) valorables económicamente al momento de la evaluación.

0. Carga de las librerías de trabajo

In [ ]:
import numpy as np
import pandas as pd

# Librerias especificas
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

1. Cargar los datos de trabajo de la base de datos BaseAAA

In [ ]:
nxl='/content/2. LavadoActivos.xlsx'
XDB=pd.read_excel(nxl,sheet_name=0)
XDB.head(100)

# Seleccionamos las variables de trabajo
XD = XDB [['edad','ingresos_usd','gastos_usd', 'num_tarjetas_credito','monto_transado_tarjetas_usd','porcentaje_crecimiento_patrimonio']]
XD.head(10)
yd = XDB[['lavado_activos']]
yd.head()

,lavado_activos
0,1
1,1
2,0
3,0
4,0


2. Implementar el Modelo Naive Bayes

In [ ]:
np.set_printoptions(suppress=True,precision=3)
mnb = GaussianNB()
mnb.fit(XD,yd)

# Mostramos las medias de las variables
u = mnb.theta_
sigma = mnb.var_; sigma = np.sqrt(sigma)
print("'edad','ingresos_usd','gastos_usd','num_tarjetas_credito','monto_transado_tarjetas_usd','porcentaje_crecimiento_patrimonio'")
print(u)
print()
print("Las desviaciones son:")
print(sigma)
print()
print('los limites superiores de las variables son:',u+sigma)
print()
print('los limites inferiores de las variables son:',u-sigma)
print()


'edad','ingresos_usd','gastos_usd','num_tarjetas_credito','monto_transado_tarjetas_usd','porcentaje_crecimiento_patrimonio'
[[   45.47   6690.733  3601.75      1.955  3090.464    44.687]
 [   44.3   70262.304 38707.284     2.016 33835.62     44.821]]

Las desviaciones son:
[[    14.711   6206.964   3219.016      2.535   2456.859     14.173]
 [    15.052 113412.265  65902.557      2.557  62991.391     15.479]]

los limites superiores de las variables son: [[    60.18   12897.697   6820.765      4.49    5547.323     58.86 ]
 [    59.352 183674.569 104609.842      4.574  96827.011     60.299]]

los limites inferiores de las variables son: [[    30.759    483.768    382.734     -0.581    633.605     30.514]
 [    29.248 -43149.96  -27195.273     -0.541 -29155.771     29.342]]



/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


**Análisis de resultados**

El análisis de las medias y los rangos definidos entre 0 y 1, muestra que variables como la edad, los ingresos, el número de tarjetas de crédito y el porcentaje de crecimiento del patrimonio presentan comportamientos muy similares entre los clientes de bajo riesgo y alto riesgo, con rangos que se superponen casi por completo. Por otro lado, las variables relacionadas con el comportamiento transaccional específicamente los gastos mensuales y el monto transado en tarjetas, muestran diferencias sustanciales tanto en sus medias como en su variabilidad, donde los clientes de alto riesgo registran valores que superan ampliamente el rango esperado para clientes con características socioeconómicas similares. Esta combinación de medias elevadas y alta dispersión en dichas variables revela inconsistencias entre el perfil económico declarado y el uso real del sistema financiero, lo que permite al modelo Naive Bayes identificar patrones atípicos asociados a posibles riesgos SARLAFT.


3. Analizar el modelo utilizando la matriz de confusión

In [ ]:
ydp = mnb.predict(XD)
cm = confusion_matrix(yd,ydp)
print(cm)

# Métricas de la matriz de confusión
VN = cm[0,0]
FP = cm[0,1]
FN = cm[1,0]
VP = cm[1,1]
TDatos = len(XDB)

# 1. Exactitud
Ex = (VP+VN)/TDatos
print("Exactitud: ",Ex)

# 2. Tasa error
TEr = (FP+FN)/TDatos
print("Tasa error: ",TEr)

# 3. Sensibilidad
Se = VP/(VP+FN)
print("Sensibilidad: ",Se)

# 4. Especificidad
Es = VN/(VN+FP)
print("Especificidad: ",Es)

# 5. Precisión
Pr = VP/(VP+FP)
print("Precisión: ",Pr)

# 6. Predicción negativa
PrN = VN/(VN+FN)
print("Predicción negativa: ",PrN)


[[2179   44]
 [ 145  782]]
Exactitud:  0.94
Tasa error:  0.06
Sensibilidad:  0.8435814455231931
Especificidad:  0.9802069275753487
Precisión:  0.9467312348668281
Predicción negativa:  0.9376075731497419


**Análisis de resultados**

La matriz de confusión evidencia que el modelo Naive Bayes tiene un desempeño sólido para la detección de riesgo SARLAFT, con una exactitud del 94% y una tasa de error del 6%, lo que indica que la gran mayoría de los clientes fueron clasificados correctamente. La sensibilidad del 84% muestra que el modelo logra identificar la mayor parte de los clientes realmente riesgosos. Por su parte, la especificidad del 98% indica que casi todos los clientes normales son reconocidos como tales, evitando generar falsas alarmas innecesarias. La precisión del 94% confirma que cuando el sistema señala a un cliente como sospechoso, en la gran mayoría de los casos tiene razón, lo que brinda confianza operativa a los analistas. Finalmente, la predicción negativa del 93% evidencia que cuando el modelo clasifica a un cliente como normal, usualmente acierta, aunque ese pequeño porcentaje restante corresponde a los casos riesgosos que no fueron detectados. En conjunto, estas métricas muestran un modelo confiable, eficiente y coherente con las necesidades de prevención del lavado de activos.

4. Se evalua un solicitante

In [ ]:
XP = [58, 31692, 19139,2, 10493, 39.61] # edad, ingresos_usd, gastos_usd, num_tarjetas_credito, monto_transado_tarjetas_usd, porcentaje_crecimiento_patrimonio
ydc = mnb.predict([XP])
print(ydc)

if ydc==1:
  print("El cliente posee alto riesgo de incurrir en lavados de activos")
else:
  print("El cliente no posee un riesgo alto de incurrir en lavado de activos")

[1]
El cliente posee alto riesgo de incurrir en lavados de activos


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


**Análisis de resultados**

En esta etapa se evalúa un solicitante utilizando el modelo Naive Bayes previamente entrenado, tomando como entrada un conjunto de datos que provienen de la base de datos de la entidad financiera.
Con base en la información registrada en la base de datos, el resultado clasifica al solicitante como cliente con alto riesgo de incurrir en lavado de activos.